# Generated by Django 6.0.4 on 2026-04-21 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
